/*
店の一覧を表示しよう.エリアも併せて表示すること.

取得項目は以下とする
 AREA_CD	エリア店インデックスマスタ.エリアCD
 AREA_NAME	エリアマスタ.エリア名
 MISE_CD	店マスタ.店CD
 MISE_NAME	店マスタ.店名
 TEL		店マスタ.電話番号

以下の項目でソートすること
 MISE_CD	店マスタ.店CD

*/

SELECT MS_AREA_MISE_IDX.AREA_CD, MS_AREA.AREA_NAME, MS_MISE.MISE_CD,
	MS_MISE.MISE_NAME, MS_MISE.TEL
FROM MS_MISE
RIGHT JOIN MS_AREA_MISE_IDX ON MS_AREA_MISE_IDX.MISE_CD = MS_MISE.MISE_CD
RIGHT JOIN MS_AREA ON MS_AREA_MISE_IDX.AREA_CD = MS_AREA.AREA_CD
ORDER BY MS_MISE.MISE_CD